### PR TITLE
Stable null safety release

### PR DESCRIPTION
**Pull request by stargazing-dino**

### CODE REVIEW

**Comment by gmpassos** [comment]
For me this version is stable. I'm using it without any issue.

**Comment by stargazing-dino** [comment]
No, I meant "stable" as in just removing the `-nullsafety` suffix as flutter null safety is in stable now and there's no need for it. In practice it means the library will just get a null-safety tag on pub and people will no longer need to specify the exact beta version in their pubspec if they're on ^2.12 sdk

**Comment by gmpassos** [comment]
Yes,I was just reaffirming that it's stable in my projects.

Note, the version should be 2.0.1, since package version resolution have some issues to understand that the 2.0.0-nullx is lower than 2.0.0, and what we want is to have the new version as the highest version.

**Comment by filiph** [comment]
Thanks for the bump! The stable 2.0.0 version is published.

**Comment by filiph** [comment]
Oh, I just noticed your 2.0.1 note, @gmpassos. Please let me know if you have issues and I'll bump the version further.

**Comment by gmpassos** [comment]
Thanks!

**Comment by gmpassos** [comment]
The issue with the version happens with a dart migration command: `dart pub upgrade --null-safety`

**Pull request closed without merging**
